name: ZN-M2 OpenWRT 24.10 官方纯净版（含NSS加速）
on:
  workflow_dispatch:

jobs:
  build_pure_with_nss:
    runs-on: ubuntu-22.04
    steps:
      - name: 1. 安装编译依赖（含NSS必需组件）
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/*
          sudo apt update -y
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip zlib1g-dev \
            file wget llvm llvm-dev lld

      - name: 2. 克隆OpenWRT 24.10官方源码
        run: |
          git clone https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          git checkout openwrt-24.10
          git pull

      - name: 3. 仅引入LibWRT核心NSS组件
        run: |
          cd openwrt
          mkdir -p package/libwrt-nss
          git clone -b k6.12-nss --single-branch https://github.com/LiBwrt/openwrt-6.x.git temp-nss
          mv temp-nss/package/kernel/qca-nss-dp package/libwrt-nss/
          mv temp-nss/package/kernel/qca-nss-ecm package/libwrt-nss/
          mv temp-nss/package/kernel/qca-nss-gmac package/libwrt-nss/
          mv temp-nss/package/kernel/qca-nss-ppe package/libwrt-nss/
          mkdir -p target/linux/qualcommax/patches-6.12/nss/
          mv temp-nss/target/linux/qualcommax/patches-6.12/nss/* target/linux/qualcommax/patches-6.12/nss/
          rm -rf temp-nss

      - name: 4. 添加ZN-M2设备支持（含NSS适配）
        run: |
          cd openwrt
          # 创建设备树目录
          mkdir -p target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/
          # 用printf创建设备树（避免YAML语法冲突）
          printf '/dts-v1/;\n#include "ipq6000-cmiot.dtsi"\n#include <dt-bindings/gpio/gpio.h>\n#include <dt-bindings/input/input.h>\n\n/ {\n    model = "ZN M2";\n    compatible = "zn,m2", "qcom,ipq6018";\n\n    aliases {\n        led-boot = &led_power;\n        led-failsafe = &led_power;\n        led-running = &led_power;\n        led-upgrade = &led_power;\n    };\n\n    leds {\n        compatible = "gpio-leds";\n        led_power: power {\n            label = "blue:power";\n            gpios = <&tlmm 58 GPIO_ACTIVE_HIGH>;\n        };\n    };\n\n    keys {\n        compatible = "gpio-keys";\n        reset {\n            label = "reset";\n            gpios = <&tlmm 63 GPIO_ACTIVE_LOW>;\n            linux,code = <KEY_RESTART>;\n            debounce-interval = <60>;\n        };\n    };\n};\n\n// NSS加速节点\n&nss_dp {\n    status = "okay";\n    qcom,nss-dp-phy-sel = <0x0>;\n};\n\n&nss_gmac0 {\n    status = "okay";\n    label = "eth0";\n};\n\n&nss_gmac1 {\n    status = "okay";\n    label = "eth1";\n};\n\n// 基础硬件\n&wifi {\n    status = "okay";\n    qcom,ath11k-calibration-variant = "ZN-M2";\n};\n\n&usb3 {\n    status = "okay";\n};\n\n&usb3_phy {\n    status = "okay";\n};\n' > target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6000-m2.dts

          # 用printf添加设备定义
          printf '\ndefine Device/qcom_ipq6000_m2\n  $(call Device/FitImage)\n  $(call Device/UbiFit)\n  DEVICE_VENDOR := ZN\n  DEVICE_MODEL := M2\n  DEVICE_DTS := qcom/ipq6000-m2\n  DEVICE_PACKAGES := kmod-usb3 kmod-usb-dwc3-qcom kmod-leds-gpio kmod-ath11k-ahb \\\n                     kmod-qca-nss-dp kmod-qca-nss-ecm kmod-qca-nss-gmac kmod-qca-nss-ppe\n  SUPPORTED_DEVICES += ipq6000-m2\nendef\nTARGET_DEVICES += qcom_ipq6000_m2\n' >> target/linux/qualcommax/image/ipq60xx.mk

      - name: 5. 配置编译选项（官方+NSS）
        run: |
          cd openwrt
          # 基础目标
          echo 'CONFIG_TARGET_qualcommax=y' >> .config
          echo 'CONFIG_TARGET_qualcommax_ipq60xx=y' >> .config
          echo 'CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_qcom_ipq6000_m2=y' >> .config
          # 官方基础功能
          echo 'CONFIG_PACKAGE_luci=y' >> .config
          echo 'CONFIG_PACKAGE_luci-ssl=y' >> .config
          echo 'CONFIG_TARGET_ROOTFS_SQUASHFS=y' >> .config
          echo 'CONFIG_PACKAGE_opkg=y' >> .config
          echo 'CONFIG_PACKAGE_wpad-basic-wifi=y' >> .config
          # NSS核心组件
          echo 'CONFIG_PACKAGE_kmod-qca-nss-dp=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-qca-nss-ecm=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-qca-nss-gmac=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-qca-nss-ppe=y' >> .config
          echo 'CONFIG_KERNEL_NET_NSS=y' >> .config
          # 禁用非必需功能
          echo 'CONFIG_PACKAGE_libwrt=n' >> .config
          echo 'CONFIG_PACKAGE_luci-app-*=n' >> .config
          echo 'CONFIG_PACKAGE_kmod-wireguard=n' >> .config
          # 同步配置
          make defconfig

      - name: 6. 更新Feeds+索引NSS组件
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -p libwrt-nss -a

      - name: 7. 下载依赖包
        run: |
          cd openwrt
          make download -j$(nproc)
          find dl -size 0 -delete
          rm -rf $(find dl -type f -name "*.sha256" -print)

      - name: 8. 编译固件（单线程）
        run: |
          cd openwrt
          make -j1 V=s
          # 验证固件
          echo "=== 固件列表 ==="
          ls -l bin/targets/qualcommax/ipq60xx/*.bin
          echo "=== NSS驱动验证 ==="
          ls -l bin/targets/qualcommax/ipq60xx/packages/kmod-qca-nss-*.ipk

      - name: 9. 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: ZN-M2_OpenWRT_24.10_Official_NSS
          path: |
            openwrt/bin/targets/qualcommax/ipq60xx/openwrt-qualcommax-ipq60xx-qcom_ipq6000_m2-squashfs-factory.bin
            openwrt/bin/targets/qualcommax/ipq60xx/openwrt-qualcommax-ipq60xx-qcom_ipq6000_m2-squashfs-sysupgrade.bin
