name: ZN-M2 IPQ6000 专用固件编译（确保硬件支持）

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget unzip gcc g++ make \
            libncurses5-dev libssl-dev python3 rsync file

      - name: 获取IPQ6000专用源码（LibWRT稳定分支）
        run: |
          # 使用专为IPQ6000优化的LibWRT分支（非官方主线）
          git clone https://github.com/LiBwrt/openwrt-6.x.git openwrt
          cd openwrt
          git checkout k6.1-nss  # 6.1内核稳定版，对IPQ6000支持完善
          
          # 配置国内源加速
          sed -i 's#https://github.com/openwrt#https://mirror.sjtu.edu.cn/git/openwrt#' feeds.conf.default
          
          # 更新并安装所有必要组件（包含IPQ6000驱动）
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 配置ZN-M2设备（IPQ6000专用）
        run: |
          cd openwrt
          
          # 加载IPQ6000基础配置
          echo "CONFIG_TARGET_qualcommax=y" >> .config
          echo "CONFIG_TARGET_qualcommax_ipq60xx=y" >> .config
          echo "CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_qcom_ipq6000_m2=y" >> .config
          
          # 强制添加IPQ6000必需驱动
          echo "CONFIG_PACKAGE_kmod-qca-nss-dp=y" >> .config  # NSS硬件加速
          echo "CONFIG_PACKAGE_kmod-qca-nss-ecm=y" >> .config
          echo "CONFIG_PACKAGE_kmod-usb-dwc3-qcom=y" >> .config  # USB驱动
          echo "CONFIG_PACKAGE_kmod-ath11k=y" >> .config  # 无线驱动
          echo "CONFIG_PACKAGE_ath11k-firmware-qcn9074=y" >> .config  # 无线固件
          
          # 基础功能组件
          echo "CONFIG_PACKAGE_luci=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-firewall=y" >> .config
          echo "CONFIG_PACKAGE_openssh-server=y" >> .config
          
          # 生成配置并验证
          make defconfig
          
          # 关键验证：确保IPQ6000驱动被正确勾选
          grep "CONFIG_PACKAGE_kmod-ath11k=y" .config || { echo "无线驱动未配置"; exit 1; }
          grep "CONFIG_TARGET_DEVICE_qualcommax_ipq60xx_DEVICE_qcom_ipq6000_m2=y" .config || { echo "设备配置失败"; exit 1; }

      - name: 编译固件（带详细日志）
        run: |
          cd openwrt
          make -j$(nproc) V=s 2>&1 | tee compile.log

      - name: 验证固件完整性
        run: |
          cd openwrt/bin/targets/qualcommax/ipq60xx
          # 检查是否包含IPQ6000-M2固件
          ls -l *qcom_ipq6000_m2*.bin || { echo "未生成目标固件"; exit 1; }
          # 检查固件中是否包含关键驱动
          binwalk -e *qcom_ipq6000_m2*.bin | grep "ath11k" || { echo "无线驱动缺失"; exit 1; }

      - name: 上传可用固件
        uses: actions/upload-artifact@v4
        with:
          name: zn-m2-ipq6000-working-firmware
          path: openwrt/bin/targets/qualcommax/ipq60xx/*qcom_ipq6000_m2*.bin
          retention-days: 14
    
