name: ZN-M2 IPQ6000 固件（修复分支问题）

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget unzip gcc g++ make \
            libncurses5-dev libssl-dev python3 rsync file

      - name: 获取源码并验证NSS分支（关键修复）
        run: |
          # 克隆LibWRT仓库
          git clone https://github.com/LiBwrt/openwrt-6.x.git openwrt
          cd openwrt
          
          # 列出所有可用分支，确保NSS分支存在
          echo "=== 可用分支列表 ==="
          git branch -r
          
          # 尝试多个可能的NSS分支（按优先级）
          NSS_BRANCHES=("main" "dev-nss" "k6.12-nss" "k5.15-nss")
          FOUND_BRANCH=""
          
          for branch in "${NSS_BRANCHES[@]}"; do
            if git checkout "$branch"; then
              FOUND_BRANCH="$branch"
              echo "=== 成功切换到NSS分支: $branch ==="
              break
            fi
          done
          
          # 如果没有找到可用分支，终止编译
          if [ -z "$FOUND_BRANCH" ]; then
            echo "错误：未找到任何NSS分支"
            exit 1
          fi
          
          # 清理非官方插件源
          cat > feeds.conf.default << 'EOF'
          src-git base https://mirror.sjtu.edu.cn/git/openwrt/base.git
          src-git packages https://mirror.sjtu.edu.cn/git/openwrt/packages.git
          src-git luci https://mirror.sjtu.edu.cn/git/openwrt/luci.git
          EOF
          
          # 更新并安装官方组件
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # 删除非官方插件包
          rm -rf package/libwrt/package/utils/
          rm -rf package/libwrt/package/emortal/
          rm -rf package/libwrt/package/feeds/

      - name: 配置固件（官方组件+NSS加速）
        run: |
          cd openwrt
          
          # 设备配置
          echo "CONFIG_TARGET_qualcommax=y" >> .config
          echo "CONFIG_TARGET_qualcommax_ipq60xx=y" >> .config
          echo "CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_qcom_ipq6000_m2=y" >> .config
          
          # NSS加速驱动
          echo "CONFIG_PACKAGE_kmod-qca-nss-dp=y" >> .config
          echo "CONFIG_PACKAGE_kmod-qca-nss-ecm=y" >> .config
          echo "CONFIG_PACKAGE_kmod-qca-nss-gmac=y" >> .config
          echo "CONFIG_PACKAGE_qca-nss-clients=y" >> .config
          
          # 官方驱动和组件
          echo "CONFIG_PACKAGE_kmod-ath11k=y" >> .config
          echo "CONFIG_PACKAGE_ath11k-firmware-qcn9074=y" >> .config
          echo "CONFIG_PACKAGE_kmod-usb-dwc3-qcom=y" >> .config
          echo "CONFIG_PACKAGE_luci=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-firewall=y" >> .config
          echo "CONFIG_PACKAGE_openssh-server=y" >> .config
          
          make defconfig
          
          # 验证配置
          grep "CONFIG_PACKAGE_kmod-qca-nss-dp=y" .config || { echo "NSS驱动缺失"; exit 1; }

      - name: 编译固件
        run: |
          cd openwrt
          make -j$(nproc) V=s 2>&1 | tee compile.log

      - name: 验证固件
        run: |
          cd openwrt/bin/targets/qualcommax/ipq60xx
          ls -l *qcom_ipq6000_m2*.bin || { echo "未生成目标固件"; exit 1; }
          binwalk -e *qcom_ipq6000_m2*.bin | grep -q "nss-dp" || { echo "NSS驱动缺失"; exit 1; }

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: zn-m2-ipq6000-firmware
          path: openwrt/bin/targets/qualcommax/ipq60xx/*qcom_ipq6000_m2*.bin
          retention-days: 14
    
